# Generated by Django 3.2.23 on 2023-12-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='city',
            field=models.CharField(max_length=255, null=True, verbose_name='城市'),
        ),
    ]
