# Generated by Django 3.2.23 on 2023-12-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApp', '0002_transaction_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='city',
            field=models.CharField(max_length=255, verbose_name='城市'),
        ),
    ]
