# Generated by Django 3.2.23 on 2023-12-17 04:45

from django.db import migrations, models
import maeApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('maeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to=maeApp.models.user_directory_path)),
            ],
        ),
        migrations.RenameModel(
            old_name='File',
            new_name='Img',
        ),
    ]
